name: Update MoneyPuck Data

on:
  schedule:
    - cron: "0 9 * * *"  # 4 AM ET during Standard Time (Nov–Mar)
    - cron: "0 8 * * *"  # 4 AM ET during Daylight Saving Time (Mar–Nov)
  workflow_dispatch:

permissions:
  contents: write  # Ensure GitHub Actions can push

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Debug - List all files
        run: find . -type f

      - name: Run data update script
        run: python Money_Puck_Data.py

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/willcote15/Money_Puck_Data.git
          git add data/24-25_skaters_data.csv
          git commit -m "Updated skaters data" || echo "No changes to commit"
          git push origin main
