name: Update MoneyPuck Data

on:
  schedule:
    - cron: "0 4 * * *"  # Runs every day at 4 AM UTC
  workflow_dispatch:  # Allows manual runs

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Debug - List all files with full details
        run: find . -type f  # Lists all files to check script location

      - name: Run data update script
        run: python Money_Puck_Data.py
        working-directory: ${{ github.workspace }}

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/skaters_data_24-25.csv
          git commit -m "Updated skaters data" || echo "No changes to commit"
          git push https://x-access-token:${GH_TOKEN}@github.com/willcote15/Money_Puck_Data.git

